import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const SOURCES = [
  // ─── Tech News (10) ───────────────────────────────────────────────
  {
    name: "TechCrunch",
    type: "rss" as const,
    url: "https://techcrunch.com/feed/",
    trustTier: "reputed_press" as const,
    tags: ["tech news", "startups", "ai"],
  },
  {
    name: "The Verge",
    type: "rss" as const,
    url: "https://www.theverge.com/rss/index.xml",
    trustTier: "reputed_press" as const,
    tags: ["tech news", "culture", "ai"],
  },
  {
    name: "Wired",
    type: "rss" as const,
    url: "https://www.wired.com/feed/rss",
    trustTier: "reputed_press" as const,
    tags: ["tech news", "culture", "science"],
  },
  {
    name: "ArXiv CS",
    type: "rss" as const,
    url: "https://rss.arxiv.org/rss/cs",
    trustTier: "research_university" as const,
    tags: ["research", "papers", "computer science"],
  },
  {
    name: "MIT Tech Review",
    type: "rss" as const,
    url: "https://www.technologyreview.com/feed/",
    trustTier: "reputed_press" as const,
    tags: ["tech news", "ai", "research"],
  },
  {
    name: "Forbes Tech",
    type: "rss" as const,
    url: "https://www.forbes.com/innovation/feed2",
    trustTier: "reputed_press" as const,
    tags: ["tech news", "business", "ai"],
  },
  {
    name: "CNET",
    type: "rss" as const,
    url: "https://www.cnet.com/rss/news/",
    trustTier: "reputed_press" as const,
    tags: ["tech news", "reviews", "consumer tech"],
  },
  {
    name: "Engadget",
    type: "rss" as const,
    url: "https://www.engadget.com/rss.xml",
    trustTier: "reputed_press" as const,
    tags: ["tech news", "gadgets", "consumer tech"],
  },
  {
    name: "ZDNet",
    type: "rss" as const,
    url: "https://www.zdnet.com/news/rss.xml",
    trustTier: "reputed_press" as const,
    tags: ["tech news", "enterprise", "ai"],
  },
  {
    name: "InfoQ",
    type: "rss" as const,
    url: "https://feed.infoq.com/",
    trustTier: "reputed_press" as const,
    tags: ["tech news", "development", "architecture"],
  },

  // ─── AI/ML/Data Science (8) ───────────────────────────────────────
  {
    name: "Towards Data Science",
    type: "rss" as const,
    url: "https://towardsdatascience.com/feed",
    trustTier: "influencer" as const,
    tags: ["ai", "data science", "ml", "tutorials"],
  },
  {
    name: "Machine Learning Mastery",
    type: "rss" as const,
    url: "https://machinelearningmastery.com/feed/",
    trustTier: "influencer" as const,
    tags: ["ml", "tutorials", "deep learning"],
  },
  {
    name: "Papers With Code",
    type: "rss" as const,
    url: "https://paperswithcode.com/latest",
    trustTier: "research_university" as const,
    tags: ["ai", "research", "papers", "ml"],
  },
  {
    name: "Kaggle Blog",
    type: "rss" as const,
    url: "https://medium.com/feed/@kaggle",
    trustTier: "official_vendor" as const,
    tags: ["data science", "ml", "competitions"],
  },
  {
    name: "OpenAI Blog",
    type: "rss" as const,
    url: "https://openai.com/blog/rss.xml",
    trustTier: "official_vendor" as const,
    tags: ["ai", "llm", "openai"],
  },
  {
    name: "DeepMind Blog",
    type: "rss" as const,
    url: "https://deepmind.google/blog/rss.xml",
    trustTier: "official_vendor" as const,
    tags: ["ai", "research", "deepmind"],
  },
  {
    name: "Google AI Blog",
    type: "rss" as const,
    url: "https://blog.google/technology/ai/rss/",
    trustTier: "official_vendor" as const,
    tags: ["ai", "research", "google"],
  },
  {
    name: "Fast.ai",
    type: "rss" as const,
    url: "https://www.fast.ai/atom.xml",
    trustTier: "influencer" as const,
    tags: ["ml", "deep learning", "tutorials"],
  },

  // ─── Design/UX (6) ────────────────────────────────────────────────
  {
    name: "Design Observer",
    type: "rss" as const,
    url: "https://designobserver.com/feed/",
    trustTier: "reputed_press" as const,
    tags: ["design", "culture", "ux"],
  },
  {
    name: "A List Apart",
    type: "rss" as const,
    url: "https://alistapart.com/main/feed/",
    trustTier: "reputed_press" as const,
    tags: ["design", "web development", "ux"],
  },
  {
    name: "UX Collective",
    type: "rss" as const,
    url: "https://uxdesign.cc/feed",
    trustTier: "influencer" as const,
    tags: ["ux", "design", "user research"],
  },
  {
    name: "Nielsen Norman Group",
    type: "rss" as const,
    url: "https://www.nngroup.com/feed/rss/",
    trustTier: "research_university" as const,
    tags: ["ux", "usability", "research"],
  },
  {
    name: "Smashing Magazine",
    type: "rss" as const,
    url: "https://www.smashingmagazine.com/feed/",
    trustTier: "reputed_press" as const,
    tags: ["design", "web development", "css"],
  },
  {
    name: "CSS-Tricks",
    type: "rss" as const,
    url: "https://css-tricks.com/feed/",
    trustTier: "influencer" as const,
    tags: ["css", "web development", "design"],
  },

  // ─── Science (8) ──────────────────────────────────────────────────
  {
    name: "Nature",
    type: "rss" as const,
    url: "https://www.nature.com/nature.rss",
    trustTier: "research_university" as const,
    tags: ["science", "research", "papers"],
  },
  {
    name: "Science Daily",
    type: "rss" as const,
    url: "https://www.sciencedaily.com/rss/all.xml",
    trustTier: "reputed_press" as const,
    tags: ["science", "research", "news"],
  },
  {
    name: "Phys.org",
    type: "rss" as const,
    url: "https://phys.org/rss-feed/",
    trustTier: "reputed_press" as const,
    tags: ["science", "physics", "technology"],
  },
  {
    name: "Quanta Magazine",
    type: "rss" as const,
    url: "https://api.quantamagazine.org/feed/",
    trustTier: "reputed_press" as const,
    tags: ["science", "math", "physics"],
  },
  {
    name: "Scientific American",
    type: "rss" as const,
    url: "https://www.scientificamerican.com/feed/",
    trustTier: "reputed_press" as const,
    tags: ["science", "research", "health"],
  },
  {
    name: "Nautilus",
    type: "rss" as const,
    url: "https://nautil.us/feed/",
    trustTier: "reputed_press" as const,
    tags: ["science", "culture", "philosophy"],
  },
  {
    name: "Popular Science",
    type: "rss" as const,
    url: "https://www.popsci.com/feed/",
    trustTier: "reputed_press" as const,
    tags: ["science", "technology", "consumer"],
  },
  {
    name: "FiveThirtyEight",
    type: "rss" as const,
    url: "https://fivethirtyeight.com/feed/",
    trustTier: "reputed_press" as const,
    tags: ["data", "statistics", "politics"],
  },

  // ─── Development (5) ──────────────────────────────────────────────
  {
    name: "Dev.to",
    type: "rss" as const,
    url: "https://dev.to/feed",
    trustTier: "influencer" as const,
    tags: ["development", "tutorials", "community"],
  },
  {
    name: "Hacker News",
    type: "rss" as const,
    url: "https://hnrss.org/frontpage",
    trustTier: "influencer" as const,
    tags: ["tech", "startups", "community"],
  },
  {
    name: "GitHub Blog",
    type: "rss" as const,
    url: "https://github.blog/feed/",
    trustTier: "official_vendor" as const,
    tags: ["development", "open source", "github"],
  },
  {
    name: "Stack Overflow Blog",
    type: "rss" as const,
    url: "https://stackoverflow.blog/feed/",
    trustTier: "influencer" as const,
    tags: ["development", "community", "programming"],
  },

  // ─── Product/Industry + Tooling + Podcasts (10) ──────────────────
  {
    name: "NVIDIA Developer Blog",
    type: "rss" as const,
    url: "https://developer.nvidia.com/blog/feed/",
    trustTier: "official_vendor" as const,
    tags: ["ai", "gpu", "developer tooling", "industry"],
  },
  {
    name: "AWS Machine Learning Blog",
    type: "rss" as const,
    url: "https://aws.amazon.com/blogs/machine-learning/feed/",
    trustTier: "official_vendor" as const,
    tags: ["ai", "ml", "cloud", "industry"],
  },
  {
    name: "Microsoft Research",
    type: "rss" as const,
    url: "https://www.microsoft.com/en-us/research/feed/",
    trustTier: "research_university" as const,
    tags: ["ai", "research", "ml", "industry"],
  },
  {
    name: "Google Research Blog",
    type: "rss" as const,
    url: "https://research.google/blog/rss/",
    trustTier: "official_vendor" as const,
    tags: ["ai", "research", "google", "papers"],
  },
  {
    name: "Hugging Face Blog",
    type: "rss" as const,
    url: "https://huggingface.co/blog/feed.xml",
    trustTier: "official_vendor" as const,
    tags: ["ai", "open source", "llm", "models"],
  },
  {
    name: "Figma Blog",
    type: "rss" as const,
    url: "https://www.figma.com/blog/rss.xml",
    trustTier: "official_vendor" as const,
    tags: ["design", "product", "ui", "ux"],
  },
  {
    name: "Vercel Blog",
    type: "rss" as const,
    url: "https://vercel.com/blog/rss.xml",
    trustTier: "official_vendor" as const,
    tags: ["frontend", "performance", "nextjs", "tooling"],
  },
  {
    name: "React Blog",
    type: "rss" as const,
    url: "https://react.dev/blog/rss.xml",
    trustTier: "official_vendor" as const,
    tags: ["frontend", "react", "development", "tooling"],
  },
  {
    name: "Chrome Developers",
    type: "rss" as const,
    url: "https://developer.chrome.com/blog/rss.xml",
    trustTier: "official_vendor" as const,
    tags: ["frontend", "web platform", "performance", "tooling"],
  },
  {
    name: "Practical AI Podcast",
    type: "rss" as const,
    url: "https://changelog.com/practicalai/feed",
    trustTier: "influencer" as const,
    tags: ["ai", "podcast", "ml", "industry"],
  },

  // ─── Video Channels: existing (4) ────────────────────────────────
  {
    name: "Fireship",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCsBjURrPoezykLs9EqgamOA",
    trustTier: "influencer" as const,
    tags: ["development", "ai", "tooling", "youtube"],
    channelId: "UCsBjURrPoezykLs9EqgamOA",
  },
  {
    name: "Veritasium",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCHnyfMqiRRG1u-2MsSQLbXA",
    trustTier: "influencer" as const,
    tags: ["science", "tech", "youtube"],
    channelId: "UCHnyfMqiRRG1u-2MsSQLbXA",
  },
  {
    name: "3Blue1Brown",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCYO_jab_esuFRV4b17AJtAw",
    trustTier: "influencer" as const,
    tags: ["math", "ml", "youtube", "explainers"],
    channelId: "UCYO_jab_esuFRV4b17AJtAw",
  },
  {
    name: "Two Minute Papers",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCbfYPyITQ-7l4upoX8nvctg",
    trustTier: "influencer" as const,
    tags: ["ai", "research", "youtube"],
    channelId: "UCbfYPyITQ-7l4upoX8nvctg",
  },

  // ─── Priority 1A: Design / UX YouTube Creators (12) ──────────────
  {
    name: "The Futur",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCoi6dq-gFW4u7-ykUGKIpgA",
    trustTier: "influencer" as const,
    tags: ["design", "branding", "ux", "business", "youtube"],
    channelId: "UCoi6dq-gFW4u7-ykUGKIpgA",
  },
  {
    name: "AJ&Smart",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC-QTnpAzpERcezcmqqbbwLg",
    trustTier: "influencer" as const,
    tags: ["design", "ux", "design sprints", "product", "youtube"],
    channelId: "UC-QTnpAzpERcezcmqqbbwLg",
  },
  {
    name: "DesignCourse",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCVyRiMvfUNMA1UPlDPzG5Ow",
    trustTier: "influencer" as const,
    tags: ["design", "ui", "web design", "css", "youtube"],
    channelId: "UCVyRiMvfUNMA1UPlDPzG5Ow",
  },
  {
    name: "Flux Academy",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCVmHAtJxrDMQPFMnJscc4Ag",
    trustTier: "influencer" as const,
    tags: ["design", "figma", "branding", "web design", "youtube"],
    channelId: "UCVmHAtJxrDMQPFMnJscc4Ag",
  },
  {
    name: "Juxtopposed",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC9N7oAX-ueqCnheBsm7lcCA",
    trustTier: "influencer" as const,
    tags: ["ux", "design", "product design", "career", "youtube"],
    channelId: "UC9N7oAX-ueqCnheBsm7lcCA",
  },
  {
    name: "CharliMarieTV",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCScRSwdX0t31gjTJ1sXJKBQ",
    trustTier: "influencer" as const,
    tags: ["ux", "design", "career", "freelance", "youtube"],
    channelId: "UCScRSwdX0t31gjTJ1sXJKBQ",
  },
  {
    name: "Kevin Powell",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCJZv4d5rbIKd4QHMPkcABCw",
    trustTier: "influencer" as const,
    tags: ["css", "web design", "frontend", "html", "youtube"],
    channelId: "UCJZv4d5rbIKd4QHMPkcABCw",
  },
  {
    name: "Google Design",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCnUYZLuoy1rq1aVMwx4aTzw",
    trustTier: "official_vendor" as const,
    tags: ["design", "google", "ux", "material design", "youtube"],
    channelId: "UCnUYZLuoy1rq1aVMwx4aTzw",
  },
  {
    name: "Figma",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCQsVmhSa4X-G3lHGDu8sLaw",
    trustTier: "official_vendor" as const,
    tags: ["design", "figma", "ui", "ux", "tools", "youtube"],
    channelId: "UCQsVmhSa4X-G3lHGDu8sLaw",
  },
  {
    name: "Malewicz",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCrM-KjJNmEBa2T-3QLhQhFQ",
    trustTier: "influencer" as const,
    tags: ["ui design", "ux", "design", "figma", "youtube"],
    channelId: "UCrM-KjJNmEBa2T-3QLhQhFQ",
  },
  {
    name: "Caler Edwards",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCfnkLjdEMnUgCnmqU8-E2lQ",
    trustTier: "influencer" as const,
    tags: ["figma", "design", "ui", "youtube"],
    channelId: "UCfnkLjdEMnUgCnmqU8-E2lQ",
  },
  {
    name: "UX Mastery",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCR-2nYdQMRFCmQMGwXHJG2Q",
    trustTier: "influencer" as const,
    tags: ["ux", "user research", "design", "career", "youtube"],
    channelId: "UCR-2nYdQMRFCmQMGwXHJG2Q",
  },

  // ─── Priority 1B: Frontend / Dev Tooling YouTube Creators (15) ───
  {
    name: "Traversy Media",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC29ju8bIPH5as8OGnQzwJyA",
    trustTier: "influencer" as const,
    tags: ["frontend", "web dev", "tutorials", "javascript", "youtube"],
    channelId: "UC29ju8bIPH5as8OGnQzwJyA",
  },
  {
    name: "Web Dev Simplified",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCFbNIlppjAuEX4znoulh0Cw",
    trustTier: "influencer" as const,
    tags: ["frontend", "javascript", "react", "web dev", "youtube"],
    channelId: "UCFbNIlppjAuEX4znoulh0Cw",
  },
  {
    name: "Theo (t3.gg)",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCbmNph6atAoGfqLoCL_duAg",
    trustTier: "influencer" as const,
    tags: ["typescript", "react", "nextjs", "web dev", "youtube"],
    channelId: "UCbmNph6atAoGfqLoCL_duAg",
  },
  {
    name: "Jack Herrington",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC6vRUjYqDFI2YLXVFBLiufA",
    trustTier: "influencer" as const,
    tags: ["react", "typescript", "frontend", "architecture", "youtube"],
    channelId: "UC6vRUjYqDFI2YLXVFBLiufA",
  },
  {
    name: "The Net Ninja",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCW5YeuERMmlnqo4oq8vwUpg",
    trustTier: "influencer" as const,
    tags: ["web dev", "tutorials", "javascript", "frontend", "youtube"],
    channelId: "UCW5YeuERMmlnqo4oq8vwUpg",
  },
  {
    name: "Academind",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCSJbGtTlrDami-tDGPe5V8w",
    trustTier: "influencer" as const,
    tags: ["web dev", "react", "nodejs", "tutorials", "youtube"],
    channelId: "UCSJbGtTlrDami-tDGPe5V8w",
  },
  {
    name: "Codevolution",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC80PWRj_ZU8Zu0HSMNVwKWw",
    trustTier: "influencer" as const,
    tags: ["react", "nextjs", "typescript", "tutorials", "youtube"],
    channelId: "UC80PWRj_ZU8Zu0HSMNVwKWw",
  },
  {
    name: "Coding Train",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCvjgXvBlbQiydffZU7m1_aw",
    trustTier: "influencer" as const,
    tags: ["creative coding", "p5js", "javascript", "algorithms", "youtube"],
    channelId: "UCvjgXvBlbQiydffZU7m1_aw",
  },
  {
    name: "Dev Ed",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UClb90NQgewpiuLce3EY8hCQ",
    trustTier: "influencer" as const,
    tags: ["web dev", "react", "javascript", "tutorials", "youtube"],
    channelId: "UClb90NQgewpiuLce3EY8hCQ",
  },
  {
    name: "Wes Bos",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCoebwHSTvwalADTJhps0emA",
    trustTier: "influencer" as const,
    tags: ["web dev", "css", "javascript", "tooling", "youtube"],
    channelId: "UCoebwHSTvwalADTJhps0emA",
  },
  {
    name: "Programming with Mosh",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCWv7vMbMWH4-V0ZXdmDpPBA",
    trustTier: "influencer" as const,
    tags: ["programming", "web dev", "tutorials", "javascript", "youtube"],
    channelId: "UCWv7vMbMWH4-V0ZXdmDpPBA",
  },
  {
    name: "Sam Selikoff",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCv8ZBwWERHDfVV5I-YhzLUQ",
    trustTier: "influencer" as const,
    tags: ["react", "testing", "frontend", "tooling", "youtube"],
    channelId: "UCv8ZBwWERHDfVV5I-YhzLUQ",
  },
  {
    name: "Scott Tolinski",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCyU5wkjgQYGRB0hIHMwm2Sg",
    trustTier: "influencer" as const,
    tags: ["web dev", "svelte", "javascript", "tutorials", "youtube"],
    channelId: "UCyU5wkjgQYGRB0hIHMwm2Sg",
  },
  {
    name: "ByteGrad",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCJtbbAYRFXHCdRrKA5DCACA",
    trustTier: "influencer" as const,
    tags: ["nextjs", "react", "typescript", "web dev", "youtube"],
    channelId: "UCJtbbAYRFXHCdRrKA5DCACA",
  },
  {
    name: "Matt Pocock",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCswG6FSbgZjbm1Vh5ebI-sjg",
    trustTier: "influencer" as const,
    tags: ["typescript", "web dev", "tooling", "youtube"],
    channelId: "UCswG6FSbgZjbm1Vh5ebI-sjg",
  },

  // ─── Priority 2: AI / ML Research + Explainers (13) ─────────────
  {
    name: "Yannic Kilcher",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCZHmQk67mSJgfCCTn7xBfew",
    trustTier: "influencer" as const,
    tags: ["ai", "research", "papers", "ml", "youtube"],
    channelId: "UCZHmQk67mSJgfCCTn7xBfew",
  },
  {
    name: "Lex Fridman",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCSHZKyawb77ixDdsGog4iWA",
    trustTier: "influencer" as const,
    tags: ["ai", "research", "interviews", "ml", "youtube"],
    channelId: "UCSHZKyawb77ixDdsGog4iWA",
  },
  {
    name: "StatQuest with Josh Starmer",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCtYLUTtgS3k1Fg4y5tAhLbw",
    trustTier: "influencer" as const,
    tags: ["ml", "statistics", "explainers", "data science", "youtube"],
    channelId: "UCtYLUTtgS3k1Fg4y5tAhLbw",
  },
  {
    name: "AI Explained",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCwRXb5dUK4cvsHbx-rGzSgw",
    trustTier: "influencer" as const,
    tags: ["ai", "llm", "explainers", "research", "youtube"],
    channelId: "UCwRXb5dUK4cvsHbx-rGzSgw",
  },
  {
    name: "DeepLearningAI",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCcIXc5mABnE-nuCWZGnFnHQ",
    trustTier: "influencer" as const,
    tags: ["ai", "deep learning", "courses", "ml", "youtube"],
    channelId: "UCcIXc5mABnE-nuCWZGnFnHQ",
  },
  {
    name: "Sentdex",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCfzlCWGWYyIQ0aLC5w48gBQ",
    trustTier: "influencer" as const,
    tags: ["python", "ml", "programming", "data science", "youtube"],
    channelId: "UCfzlCWGWYyIQ0aLC5w48gBQ",
  },
  {
    name: "Robert Miles",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCLB7AzTwc6VFZrBsO2ucBMg",
    trustTier: "influencer" as const,
    tags: ["ai safety", "alignment", "ml", "research", "youtube"],
    channelId: "UCLB7AzTwc6VFZrBsO2ucBMg",
  },
  {
    name: "Hugging Face",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCHlNU7kIZhRgSbhHvFoy72w",
    trustTier: "official_vendor" as const,
    tags: ["ai", "models", "open source", "llm", "youtube"],
    channelId: "UCHlNU7kIZhRgSbhHvFoy72w",
  },
  {
    name: "Weights & Biases",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCBBcK6lBkHN7__CiKGM-1_g",
    trustTier: "official_vendor" as const,
    tags: ["mlops", "research", "ml", "tools", "youtube"],
    channelId: "UCBBcK6lBkHN7__CiKGM-1_g",
  },
  {
    name: "NVIDIA Developer",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCBHcMnPO97K3MkqflcoExzQ",
    trustTier: "official_vendor" as const,
    tags: ["ai", "gpu", "developer tools", "deep learning", "youtube"],
    channelId: "UCBHcMnPO97K3MkqflcoExzQ",
  },
  {
    name: "ML Street Talk",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCMLtBahI5DMrt0j-MuDLObw",
    trustTier: "influencer" as const,
    tags: ["ml", "research", "discussions", "ai", "youtube"],
    channelId: "UCMLtBahI5DMrt0j-MuDLObw",
  },
  {
    name: "Andrej Karpathy",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCPk8m_r6fkUSWeb09GnrmCQ",
    trustTier: "influencer" as const,
    tags: ["ai", "deep learning", "llm", "research", "youtube"],
    channelId: "UCPk8m_r6fkUSWeb09GnrmCQ",
  },
  {
    name: "AI Coffee Break with Letitia",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCobqgqE4i5pU1UkByV9IZFw",
    trustTier: "influencer" as const,
    tags: ["ai", "research", "papers", "explainers", "youtube"],
    channelId: "UCobqgqE4i5pU1UkByV9IZFw",
  },

  // ─── Priority 3: Mixed / General Science & Tech (10) ─────────────
  {
    name: "Computerphile",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC9-y-6csu5WGm29I7JiwpnA",
    trustTier: "influencer" as const,
    tags: ["cs", "programming", "concepts", "tech", "youtube"],
    channelId: "UC9-y-6csu5WGm29I7JiwpnA",
  },
  {
    name: "Sebastian Lague",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCmtyQOKKmrMVaKuRXz02jbQ",
    trustTier: "influencer" as const,
    tags: ["creative coding", "games", "algorithms", "visual", "youtube"],
    channelId: "UCmtyQOKKmrMVaKuRXz02jbQ",
  },
  {
    name: "freeCodeCamp",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC8butISFwT-Wl7EV0hUK0BQ",
    trustTier: "influencer" as const,
    tags: ["programming", "web dev", "tutorials", "open source", "youtube"],
    channelId: "UC8butISFwT-Wl7EV0hUK0BQ",
  },
  {
    name: "Google for Developers",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC295-Dw0tDd-M0ii6u-oKVA",
    trustTier: "official_vendor" as const,
    tags: ["google", "developer tools", "web", "tech", "youtube"],
    channelId: "UC295-Dw0tDd-M0ii6u-oKVA",
  },
  {
    name: "Corey Schafer",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCCezIgC97PvUuR4_gbFUs5g",
    trustTier: "influencer" as const,
    tags: ["python", "programming", "tutorials", "web dev", "youtube"],
    channelId: "UCCezIgC97PvUuR4_gbFUs5g",
  },
  {
    name: "Reducible",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCK8yjNnPijkm3-pMOzQLpAQ",
    trustTier: "influencer" as const,
    tags: ["cs", "algorithms", "concepts", "visual", "youtube"],
    channelId: "UCK8yjNnPijkm3-pMOzQLpAQ",
  },
  {
    name: "Hussein Nasser",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC_eOodxvwS_H7x2uLQa-svA",
    trustTier: "influencer" as const,
    tags: ["backend", "databases", "engineering", "architecture", "youtube"],
    channelId: "UC_eOodxvwS_H7x2uLQa-svA",
  },
  {
    name: "CS Dojo",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCxAgnE7LHgFIKL9c5-EJKUA",
    trustTier: "influencer" as const,
    tags: ["algorithms", "programming", "cs", "interviews", "youtube"],
    channelId: "UCxAgnE7LHgFIKL9c5-EJKUA",
  },
  {
    name: "MIT OpenCourseWare",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCEBb1b_L6zDS3xTUrIALZOw",
    trustTier: "research_university" as const,
    tags: ["cs", "math", "science", "academic", "youtube"],
    channelId: "UCEBb1b_L6zDS3xTUrIALZOw",
  },
  {
    name: "Continuous Delivery",
    type: "youtube" as const,
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCCTVrRYhLCPfGe8bwW7e1WQ",
    trustTier: "influencer" as const,
    tags: ["devops", "ci/cd", "software engineering", "tooling", "youtube"],
    channelId: "UCCTVrRYhLCPfGe8bwW7e1WQ",
  },
];

async function main() {
  console.log("🌱 Seeding AI News Hub database...\n");

  for (const source of SOURCES) {
    const existing = await prisma.source.findFirst({
      where: { name: source.name },
    });

    if (existing) {
      console.log(`  ⏭  Skipping "${source.name}" (already exists)`);
      continue;
    }

    await prisma.source.create({ data: source });
    console.log(`  ✅ Created source: ${source.name} (${source.type})`);
  }

  const count = await prisma.source.count();
  console.log(`\n🎉 Done! ${count} sources in database.`);
}

main()
  .catch((e) => {
    console.error("Seed error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
